Repository ikhsan3adi/absensi-sekolah-qr-code, pull requests merged in 2024-07, with the labels that each got.

#81 Use https://github.com/ikhsan3adi/myth-auth to fix user registration
  composer.json
  composer.lock
Labels: bug, dependencies

#86 Update siswa & guru without updating `unique_code`
  app/Controllers/Admin/DataGuru.php
  app/Controllers/Admin/DataSiswa.php
  app/Models/GuruModel.php
  app/Models/SiswaModel.php
Labels: bug, enhancement

#91 fix: Dynamic alert bg color
  app/Views/admin/data/create/create-data-guru.php
  app/Views/admin/data/create/create-data-siswa.php
  app/Views/admin/data/data-guru.php
  app/Views/admin/data/data-siswa.php
  app/Views/admin/data/edit/edit-data-guru.php
  app/Views/admin/data/edit/edit-data-siswa.php
  app/Views/admin/jurusan/create.php
  app/Views/admin/jurusan/edit.php
  app/Views/admin/kelas/create.php
  app/Views/admin/kelas/edit.php
  app/Views/admin/kelas/index.php
  app/Views/admin/petugas/data-petugas.php
  app/Views/admin/petugas/edit-data-petugas.php
Labels: enhancement

#93 QRCode download feature
  app/Config/Routes.php
  app/Controllers/Admin/QRGenerator.php
  app/Views/admin/data/list-data-guru.php
  app/Views/admin/data/list-data-siswa.php
  app/Views/admin/generate-qr/generate-qr.php
Labels: enhancement

#92 Create QRGeneratorTest.php
  app/Controllers/Admin/QRGenerator.php
  app/Database/Migrations/2023-08-18-000003_CreateDB.php
  composer.json
  tests/unit/QRGeneratorTest.php
Labels: test

#96 chore: Create siswa & guru seeder
  app/Database/Seeds/GuruSeeder.php
  app/Database/Seeds/SiswaSeeder.php
Labels: test

#97 docs: Update readme & screenshots
  README.md
  screenshots/absen-guru.png
  screenshots/absen-siswa.png
  screenshots/data-guru.png
  screenshots/data-siswa.png
  screenshots/generate-qr.png
  screenshots/image_11_2023_205146.jpeg
  screenshots/image_12_2023_205221.jpeg
  screenshots/image_13_2023_205243.jpeg
  screenshots/image_14_2023_205256.jpeg
  screenshots/image_15_2023_205322.jpeg
  screenshots/image_2_2023_20525.jpeg
  screenshots/image_3_2023_20539.jpeg
  screenshots/laporan.png
  screenshots/login.jpeg
  screenshots/qr-scanner.jpeg
  screenshots/ubah-kehadiran.jpeg
Labels: documentation

#98 style: Remove action button text
  app/Views/admin/data/list-data-guru.php
  app/Views/admin/data/list-data-siswa.php
Labels: enhancement

#99 refactor test & QR Generator
  app/Controllers/Admin/QRGenerator.php
  tests/unit/QRGeneratorTest.php
Labels: enhancement, test

#104 fix: View not found @ kelas & jurusan forms
  app/Controllers/Admin/JurusanController.php
  app/Controllers/Admin/KelasController.php
Labels: bug

#105 fix: Dashboard error
  app/Controllers/Admin/Dashboard.php
Labels: bug

#111 Tahun ajaran dinamis
  README.md
  app/Config/AbsensiSekolah.php
  app/Controllers/Admin/GenerateLaporan.php
  app/Views/admin/data/create/create-data-guru.php
  app/Views/admin/data/create/create-data-siswa.php
  app/Views/admin/data/data-guru.php
  app/Views/admin/data/data-siswa.php
  app/Views/admin/data/edit/edit-data-guru.php
  app/Views/admin/data/edit/edit-data-siswa.php
  app/Views/admin/generate-laporan/laporan-guru.php
  app/Views/admin/generate-laporan/laporan-siswa.php
  app/Views/admin/kelas/index.php
  app/Views/admin/petugas/edit-data-petugas.php
Labels: documentation, enhancement

#112 Format tanggal bahasa indonesia di laporan
  app/Controllers/Admin/GenerateLaporan.php
  app/Views/admin/generate-laporan/laporan-guru.php
  app/Views/admin/generate-laporan/laporan-siswa.php
Labels: enhancement

#118 Refactor directory structure and update script paths
  .htaccess
  app/Views/admin/dashboard.php
  app/Views/admin/generate-laporan/laporan-guru.php
  app/Views/admin/generate-laporan/laporan-siswa.php
  app/Views/scan/scan.php
  app/Views/templates/css.php
  app/Views/templates/fixed_plugin.php
  app/Views/templates/js.php
  app/Views/templates/sidebar.php
  app/Views/templates/starting_page_layout.php
  index.php
  public/assets/fonts/fonts.css
  spark
Labels: enhancement

#123 fix urutan siswa salah saat generate laporan
  app/Models/SiswaModel.php
Labels: bug

#125 Add : General Settings School
  .gitignore
  README.md
  app/Common.php
  app/Config/AbsensiSekolah.php
  app/Config/Autoload.php
  app/Config/Routes.php
  app/Config/School.php
  app/Controllers/Admin/Dashboard.php
  app/Controllers/Admin/GeneralSettings.php
  app/Controllers/Admin/GenerateLaporan.php
  app/Controllers/Admin/JurusanController.php
  app/Controllers/Admin/KelasController.php
  app/Controllers/Admin/QRGenerator.php
  app/Controllers/BaseController.php
  app/Database/Migrations/2024-07-24-083011_GeneralSettings.php
  app/Language/en/Validation.php
  app/Models/BaseModel.php
  app/Models/GeneralSettingsModel.php
  app/Models/UploadModel.php
  app/Views/admin/_messages.php
  app/Views/admin/dashboard.php
  app/Views/admin/data/data-guru.php
  app/Views/admin/data/data-siswa.php
  app/Views/admin/general-settings/index.php
  app/Views/admin/generate-laporan/laporan-guru.php
  app/Views/admin/generate-laporan/laporan-siswa.php
  app/Views/admin/kelas/index.php
  app/Views/templates/css.php
  app/Views/templates/footer.php
  app/Views/templates/sidebar.php
  public/assets/css/style.css
  public/uploads/index.html
  public/uploads/logo/index.html
  public/uploads/tmp/index.html
Labels: enhancement

#129 fix ui halaman guru dan petugas
  app/Views/admin/data/data-guru.php
  app/Views/admin/petugas/data-petugas.php
Labels: enhancement
